### ISSUE TITLE
Is there a way to re initialise ui lang?

### ISSUE THREAD

**Issue by aaronstezycki** [bendc/uilang#19]
I have a page load effect using smooth state js, and this loads the page in with Ajax (I think). This breaks UI Lang, but smooth state has a callback to initialise other script after its done its thing.

**Comment by bendc** [comment]
Closing as this isn't related to uilang per se.

**Comment by aaronstezycki** [comment]
Erm, actually I just want to know how to initialise ui lang within a callback, so actually it is?

**Comment by aaronstezycki** [comment]
There has to be a $().uilang('start'); or something similar ?

**Comment by aaronstezycki** [comment]
Sorted this myself by just putting the code within its own function. 

```
function uiLang(){
    var codeElements = document.getElementsByTagName("code")
    var i = codeElements.length
    var delimiter = "clicking on"
    ... etc
}
```

Thanks for your help dude.
